rsbakery/core/urls.py
from django.urls import path, include
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('create-recipe/', CreateRecipeView.as_view(), name='create-recipe'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='detail'),
    path('update-recipe/<int:pk>/', RecipeUpdateView.as_view(), name='update-recipe'),
    path('delete-recipe/<int:pk>/', RecipeDeleteView.as_view(), name='delete-recipe'),
    path('add/<int:pk>/', UpdateIngredient.as_view(), name='add-ingredients'),
    path('remove/<int:recipe>/<int:ingredient>/', RemoveIngredient.as_view(), name='remove-ingredients'),
    path('recipe-collection/', RecipeCollectionListView.as_view(), name='recipe-collection-list'),
    path('recipe/<int:pk>/add-comment/', AddComment.as_view(), name='add-comment'),
    path('remove-comment/<int:pk>/', RemoveComment.as_view(), name='remove-comment'),
    path('likes/', Likes.as_view(), name='likes'),
    path('update-collections/', UpdateCollectionView.as_view(), name='update-collections'),
    path('contact/', ContactView.as_view(), name='contact-us'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),


    
]

rsbakery/culinary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('products.urls')),
    path('sales/', include('sales.urls')),
    path('users/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rsbakery/products/urls.py
from django.urls import path


from .views import *

app_name = 'products'

urlpatterns = [
    path('products/', ProductListView.as_view(), name="products"),
    path('products/<int:pk>/', ProductDetailView.as_view(), name="products-detail"),

    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path('dashboard/products/', DashboardProductListView.as_view(), name="dashboard-products-list"),
    path('dashboard/products/add/', ProductCreateView.as_view(), name="dashboard-product-add"),
    path('dashboard/products/update/<int:pk>/', ProductUpdateView.as_view(), name="dashboard-product-update"),
    path('dashboard/products/delete/<int:pk>/', ProductDeleteView.as_view(), name="dashboard-product-delete"),

    path('dashboard/raw_material/', RawMaterialListView.as_view(), name="dashboard-raw-material-list"),
    path('dashboard/raw_material/add/', RawMaterialCreateView.as_view(), name="dashboard-raw-material-add"),
    # path('dashboard/raw_material/update/<int:pk>/', RawMaterialUpdateView.as_view(), name="dashboard-raw-material-update"),

    path('dashboard/stock/', StockListView.as_view(), name="dashboard-stock-list"),
    path('dashboard/stock/add/', StockCreateView.as_view(), name="dashboard-stock-add"),
    path('dashboard/stock/update/<int:pk>/', StockUpdateView.as_view(), name="dashboard-stock-update"),
    path('dashboard/stock/delete/<int:pk>/', StockDeleteView.as_view(), name="dashboard-stock-delete"),

    path('dashboard/products/stock/', ProductStockListView.as_view(), name="dashboard-product-stock-list"),
    path('dashboard/products/stock/add/', ProductStockCreateView.as_view(), name="dashboard-product-stock-add"),

    path('get_unit/', get_unit, name="get_unit"),
]

rsbakery/rsbakery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('products.urls')),
    path('sales/', include('sales.urls')),
    path('users/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'users.views.error_404'
handler500 = 'users.views.error_500'
handler403 = 'users.views.error_403'

rsbakery/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from users import views as user_views


app_name = 'users'


urlpatterns = [
    # path('register/', user_views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.ProfileView.as_view(), name='profile'),
    path('profile-update/<int:pk>/',
         user_views.ProfileUpdate.as_view(), name='update_profile'),
    path('activate/<uidb64>/<token>/',
         user_views.activate_account, name='activate'),
    path('password-change/', user_views.UserPasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name="password_change_done"),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('users:password_reset_done'),
        email_template_name='users/password_reset_email.html'
    ), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),

    path('password-reset/complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

rsbakery/core/forms.py
from django import forms
from core.models import Recipe
from django_summernote.widgets import SummernoteInplaceWidget, SummernoteWidget


class RecipeForm(forms.ModelForm):
    description = forms.CharField(widget=SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '400px'}}))
    class Meta:
        model = Recipe
        fields = ('title', 'description', 'image')
        
    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

rsbakery/core/views.py
import random
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView, View, UpdateView, DeleteView, CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.template.loader import render_to_string

from .models import *
from .forms import RecipeForm
from .utils import CustomAuthMixin
from users.views import OwnerOnlyMixin
from products.models import Product


def add_ingredient_to_recipe(user, recipe, ingredient_list):
    """Helper function to add ingredients to recipe"""
    for ingredient in ingredient_list:
        if ingredient:
            try: 
                ing = Ingredients.objects.get(name=ingredient)
            except ObjectDoesNotExist:
                ing = Ingredients.objects.create(name=ingredient, user=user)
            recipe.ingredients.add(ing)
            recipe.save()
    return recipe

def add_tag_to_recipe(user, recipe, tag_list):
    """Helper function to add tags to recipe"""
    for tag in tag_list:
        if tag:
            try:
                tg = Tags.objects.get(name=tag)
            except ObjectDoesNotExist:
                tg = Tags.objects.create(name=tag, user=user)
            recipe.tags.add(tg)
            recipe.save()
    return recipe


class AboutUsView(TemplateView):
    template_name = 'core/aboutus.html'

class ContactView(TemplateView):
    template_name = 'core/contact.html'

class IndexView(View):
    template_name = 'core/index.html'

    def get(self, request, *args, **kwargs):
        carousel_obj = CarouselObjects.objects.filter(active=True)
        if Product.objects.all().count() > 12:
            ids = Product.objects.filter(status=True).values_list('id', flat=True)
            rand_ids = random.sample(list(ids), 12)
            item_list = Product.objects.filter(id__in=rand_ids)
        else: 
            item_list = Product.objects.all()
        context = {'carousel_obj': carousel_obj, 'item_list': item_list}
        return render(request, self.template_name, context=context)



class CreateRecipeView(CustomAuthMixin, View):
    """View to create a new recipe"""

    def get(self, request, *args, **kwargs):
        form = RecipeForm()
        return render(request, 'core/recipe_form.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            tag_list = request.POST.getlist('tag')
            ingredient_list = request.POST.getlist('ingredient')
            recipe = form.save(commit=False)
            recipe.user = request.user
            recipe.save()
            # add tags to recipe
            add_tag_to_recipe(request.user, recipe, tag_list)
            # add ingredients to recipe
            add_ingredient_to_recipe(request.user, recipe, ingredient_list)
            recipe.save()
            return redirect('core:detail', recipe.id)
        return redirect('core:create-recipe')


class RecipeDetailView(CustomAuthMixin, View):
    def get(self, request, *args, **kwargs):
        recipe = Recipe.objects.get(pk=self.kwargs.get('pk'))
        user = self.request.user
        if user.is_authenticated:
            if RecipeCollection.objects.filter(user=self.request.user, recipe=recipe).exists():
                is_collection = True
            else: is_collection = False
            return render(request, 'core/recipe_detail.html', {'object': recipe, 'is_collection': is_collection})
        return render(request, 'core/recipe_detail.html', {'object': recipe})


    def post(self, request, *args, **kwargs):
        recipe = Recipe.objects.get(pk=self.kwargs.get('pk'))
        comment_input = request.POST.get('comment-input')
        if comment_input:
            comment = Comments.objects.create(comment=comment_input, user=self.request.user, recipe=recipe)
            comment.save()
        return redirect('core:detail', recipe.id)


class RecipeUpdateView(CustomAuthMixin, OwnerOnlyMixin, UpdateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'core/recipe_update_form.html'


class RecipeDeleteView(CustomAuthMixin, OwnerOnlyMixin, DeleteView):
    model = Recipe


class RecipeListView(View):
    def get(self, request, *args, **kwargs):
        queryset = Recipe.objects.all()
        if queryset:
            random_obj = random.choices(queryset)[0]
            query = request.GET.get('search')
            if query:
                queryset = queryset.filter(
                    Q(tags__name__icontains=query) | Q(ingredients__name__icontains=query) | Q(title__icontains=query)
                ).distinct()
            paginator = Paginator(queryset, 5)
            page_number = request.GET.get('page')
            queryset = paginator.get_page(page_number)
            return render(request, 'core/recipe_list.html', {
                'random_obj': random_obj,
                'queryset': queryset
            })
        else:
            return render(request, 'core/recipe_list.html', {
                # 'random_obj': random_obj,
                'queryset': queryset
            })


class UpdateIngredient(CustomAuthMixin, View):
    def get(self, request, *args, **kwargs):
        recipe = get_object_or_404(Recipe, pk=kwargs['pk'])
        return render(request, 'core/update.html', {'recipe': recipe})

    def post(self, request, *args, **kwargs):
        recipe = get_object_or_404(Recipe, pk=kwargs['pk'])
        if recipe.user==self.request.user:
            ingredient_list = request.POST.getlist('ingredient')
            add_ingredient_to_recipe(request.user, recipe, ingredient_list)
            return redirect('core:detail', recipe.id)


class RemoveIngredient(CustomAuthMixin, View):
    def get(self, request, *args, **kwargs):
        recipe = get_object_or_404(Recipe, pk=kwargs.get('recipe'))
        if recipe.user==self.request.user:
            recipe.ingredients.remove(kwargs.get('ingredient'))
            recipe.save()
            return redirect(request.META['HTTP_REFERER'])
        return redirect('core:recipes')
        

class UpdateCollectionView(CustomAuthMixin, View):
    def post(self, request, *args, **kwargs):
        recipe = get_object_or_404(Recipe, id=self.request.POST.get('pk'))
        my_collections, created = RecipeCollection.objects.get_or_create(user=self.request.user)
        if recipe in my_collections.recipe.all():
            my_collections.recipe.remove(recipe)
            my_collections.save()
            is_collection = False
        else:
            my_collections.recipe.add(recipe)
            my_collections.save()
            is_collection = True
        
        context = {
            'object': recipe,
            'my_collections': my_collections,
            'is_collection': is_collection,
        }
        
        if request.is_ajax():
            form = render_to_string('core/_update_collections.html', context, request=request)
            return JsonResponse({'form': form})
        

class RecipeCollectionListView(CustomAuthMixin, ListView):
    """Shows the Users Recipe Collection"""
    model = RecipeCollection
    template_name = 'core/recipecollection_list.html'
    paginate_by = 5

    def get_queryset(self):
        try:
            queryset = super(RecipeCollectionListView, self).get_queryset().filter(user=self.request.user)
            queryset = [x for x in queryset[0].recipe.all()]
        except IndexError:
            queryset = []
        return queryset

    
class AddComment(CustomAuthMixin, CreateView):
    model = Comments
    fields = ('comment',)

    def form_valid(self, form, **kwargs):
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.recipe = self.kwargs.get('recipe')
        comment.save()
        return super().form_valid(form, **kwargs)


class RemoveComment(CustomAuthMixin, View):
    def post(self, request, *args, **kwargs):
        comment = Comments.objects.get(pk=self.kwargs.get('pk'))
        if comment.user == self.request.user:
            comment.delete()
        return HttpResponse('success', status=200)
    
    
class Likes(CustomAuthMixin, View):
    def post(self, request, *args, **kwargs):
        recipe = get_object_or_404(Recipe, id=self.request.POST.get('pk'))
        user = self.request.user
        
        if recipe.likes.filter(id=user.id).exists():
            recipe.likes.remove(user)
            recipe.save()

        else:
            recipe.likes.add(user)
            recipe.save()

        context = {
            'object': recipe,
            'likes_count': recipe.likes_count(),
        }

        if request.is_ajax():
            form = render_to_string('core/_like_snippet.html', context, request=request)
            return JsonResponse({'form': form})

rsbakery/core/templates/core/_like_snippet.html
{% if user.is_authenticated %}
<form method="POST">
    {%csrf_token%}
    
    {% if request.user in object.likes.all %}
    <button id="likes" value="{{object.id}}" class="btn btn-outline-danger mt-3">Unlike</button>
    {% else %}
    <button id="likes" value="{{object.id}}" class="btn btn-outline-info mt-3">Like</button>
    {% endif %}
    <span class="btn mt-3">Likes: {{object.likes_count}}</span>
</form>
{% endif %}

rsbakery/core/templates/core/_post.html
<div class="card mt-3 shadow-sm p-3 mb-3 bg-white rounded">
    <div class="row no-gutters">
        <div class="col-md-4">
            <a href="{% url 'core:detail' object.id %}"><img src="{{object.get_image_url}}" class="card-img"
                    alt="..."></a>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{object.title | capfirst}}</h5>
                <p class="card-text">{{object.get_summary | safe | capfirst}}</p>
                <p class="card-text"><small class="text-muted">Created by: <span><a
                                href="{% url 'users:profile' %}">{{object.user.profile.first_name}}
                                {{object.user.profile.last_name}}</a></span> at
                        {{object.data_created | date:'d M Y'}}</small></p>
            </div>
        </div>
    </div>
</div>

rsbakery/core/templates/core/_update_collections.html
{% if user.is_authenticated %}
<form method="POST">
    {%csrf_token%}
    {% if is_collection %}
    <button type="submit" id="add-to-collections" value="{{ object.id }}" class="btn btn-outline-danger mt-3">Remove from
Collections</button>
    {%else%}
    <button type="submit" id="add-to-collections" value="{{ object.id }}" class="btn btn-outline-info mt-3">Add To
        My Collections</button>
    {%endif%}
</form>
{%endif%}

rsbakery/core/templates/core/contact.html
{% extends 'users/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<div class="imageContainer">
    <div class="container contactus">
        <div class="heading">
            <h2>Contact Us</h2>
            <p>We are happy to hear your views. Please let us know what we can do better to provide you best anyone can
                offer.</p>
        </div>
        <div class="content">
            <h3><i class="fa fa-map-marker-alt"></i> Address</h3>
            <p>Saraswatipuram, Near Primary School, Korkhana, Faizabad, 224001</p>
        </div>
        <div class="content">
            <h3><i class="fa fa-envelope"></i> Email</h3>
            <p>rsbakeryfzd@gmail.com</p>
        </div>
        <div class="content">
            <h3><i class="fa fa-phone-alt"></i> Phone</h3>
            <p>+91 7906908088</p>
        </div>

    </div>

</div>


{% endblock %}

rsbakery/core/templates/core/form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{form | crispy }}
        <button type="submit">Submit</button>
    </form>
</div>

{% endblock %}

rsbakery/core/templates/core/home.html
{% extends 'users/base.html' %}
{% block body %}

<div class="container">
    <div class="row">

        <div class="col-md-4 order-md-1 mb-4">

            <div class="card mt-3 shadow p-3 mb-3 bg-white rounded">
                <div class="row">
                    <div class="col-md-8 offset-md-2 mt-4 mb-4">
                        <img src="{{user.profile.image.url}}" class="rounded-circle card-img-top">
                    </div>
                </div>
                
                <div class="card-body">
                    <h5 class="card-title text-center">{{user.profile.first_name}} {{user.profile.last_name}}</h5>
                    <p class="text-center">{{user.profile.location}}</p>
                </div>

            </div>

        </div>

        <div class="col-md-8 order-md-2">
            
            <div class="card mt-3 shadow p-3 mb-3 bg-white rounded">
                <!-- <div class="row no-gutters">
                    <div class="col-md-4">
                        
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{object.title | capfirst}}</h5>
                            <p class="card-text">{{object.get_summary | capfirst}}</p>
                            <p class="card-text"><small class="text-muted">Created {{object.data_created}}</small></p>
                        </div>
                    </div>
                </div> -->
            <h4>Profile Summary</h4>
            <hr>
            <div>
            <h5>About Me</h5>
            <p>{{user.profile.about_me}}</p>
            </div>
            <div>
                <h5>Email</h5>
                <p>{{user.email}}</p>
            </div>

            </div>
           
        </div>

    </div>
</div>



{% endblock %}

rsbakery/core/templates/core/index.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}

{% include 'core/inner-header.html' %}

<div class="container">
    <h4 class="headingText">Our Products</h4>
    <p>Choose your favourites from our wide range of products</p>
    
    <div class="row">
        {% for item in item_list %}
        {% include 'products/_product_snippet.html' %}
        {% endfor %}
    </div>
    <div class="row">
        <div class="col text-right">
            <a class="viewAll" href="{% url 'products:products' %}">View all</a>
        </div>
    </div>
    <hr/>

    <h4 class="headingText">Browse Categories</h4>
    <p>We offer a range of products from Breads to Cakes. Choose your favourite Category.</p>

    <div class="row pb-3">
        <div class="col-md-4 col-sm-3 p-3">
            <div class="card h-100">
                <img class="card-img-top" src="{%static 'pictures/default_cake.jpg'%}" />
                <div class="card-footer">
                    <h5>Cakes</h5>
                    <p>Choose from a wide variety of Cakes</p>
                </div>
                <a href="{% url 'products:products' %}?ctg=cake" class="btn btn-block btn-outline-orange">Browse...</a>
            </div>
            
        </div>

        <div class="col-md-4 col-sm-3 p-3">
            <div class="card h-100">
                <img class="card-img-top" src="{%static 'pictures/default_cookies.jpg'%}" />
                <div class="card-footer">
                    <h5>Cookies</h5>
                    <p>Chocolate, Coconut we got 'em all</p>
                </div>
                <a href="{% url 'products:products' %}?ctg=cookies" class="btn btn-block btn-outline-orange">Browse...</a>
            </div>
            
        </div>

        <div class="col-md-4 col-sm-3 p-3">
            <div class="card h-100">
                <img class="card-img-top" src="{%static 'pictures/default_breads.jpg'%}" />
                <div class="card-footer">
                    <h5>Breads</h5>
                    <p>Fresh, soft and crispy at the same time</p>
                </div>
                <a href="{% url 'products:products' %}?ctg=bread" class="btn btn-block btn-outline-orange">Browse...</a>
            </div>
            
        </div>
    </div>
</div>

{% endblock body %}

rsbakery/core/templates/core/recipe_detail.html
{% extends 'users/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-5 mt-3">
            <div class="row">
                <div class="col-md-12">
                    <div class="card detailImg">
                        <img class="card-img-top" src="{{object.image.url}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div id="like-section" class="col-md-6">
                    {% include 'core/_like_snippet.html' %}
                    
                </div>
                <div id="collections-section" class="col-md-6">
                    {% include 'core/_update_collections.html' %}
                </div> 
            </div>
        </div>

        <div class="col-md-7 mt-3">
            <div class="row">
                <div class="col-md-6">
                    <h2>{{object.title | capfirst}}</h2>
                </div>
                <div class="col-md-6">
                    {% if object.user == request.user %}
                    <div class="dropdown">
                        <a class="btn dropdown-toggle float-right" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-pen"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a href="{% url 'core:update-recipe' object.id %}" class="dropdown-item">Update</a>
                            <a href="{% url 'core:delete-recipe' object.id %}" class="dropdown-item">Delete</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6">
                    <h5>Ingredients</h5>
                </div>
                <div class="col-md-6">
                    {% if object.user == request.user %}
                    <a href="{% url 'core:add-ingredients' object.id %}" class="btn float-right"><i
                            class="fas fa-pen"></i></a>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <ul>
                        {% for ingredient in object.ingredients.all %}
                        <li>{{ingredient|capfirst}}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row mt-3">
        <div class="col-md-12">
            <h5>Recipe</h5>
            <p>{{object.description| safe | capfirst}}</p>
            <hr/>
        </div>
        
    </div>
    <div class="row">
        <div class="col-md-12 mb-3">
            <h5>Post Comment</h5>
            <form method="POST">{% csrf_token %}
                <textarea class="form-control mb-3" id="comment-form" name="comment-input" rows="3"></textarea>
                {% if user.is_authenticated %}
                <button type="submit" class="btn btn-outline-info">Add Comment</button>
                {% else %}
                <a href="#" id="login-alert" type="submit" class="btn btn-outline-info">Add Comment</a>
                {% endif %}
            </form>

        </div>
    </div>
    <div class="row">
        <div class="col-md-12 mt-3">
            <h5>Comments</h5>
            {% for comment in object.comments %}
            <div class="row mt-3">
                <div class="col-md-1 col-xs-2">
                    <img class="img-fluid" src="{{comment.user.profile.image.url}}" />
                </div>
                <div class="col-md-11 col-xs-8">
                    <div class="">
                        <h6>{{comment.user.profile.first_name}} <small text-muted>
                                {{comment.created | date:'d M Y'}}</small></h6>
                        <p>{{comment | capfirst}}</p>
                        {% if comment.user == request.user %}
                        <form class="delete-comment" method="POST">
                            {% csrf_token %}
                            <a href="#" value="{{comment.id}}" class="delete-btn">Delete</a>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock body %}

{% block scripts %}
<script>
    $(document).ready(function (e) {
        $(document).on('click', '#add-to-collections', function (e) {
            e.preventDefault();
            var id = $(this).attr('value');

            $.ajax({
                type: "POST",
                url: "{% url 'core:update-collections' %}",
                data: {'pk': id, 'csrfmiddlewaretoken': '{{csrf_token}}'},
                dataType: 'json',
                success: function (response) {
                    $('#collections-section').html(response['form'])

                },
            });
        });

        $(document).on('click', '#login-alert', function () {
            alert('You must be logged-in to use this feature')
        });

        $(document).on('click', '.delete-btn', function (e) {
            e.preventDefault();
            let confirmation = confirm('Are you sure you want to delete this comment?');
            if (confirmation) {
                var pk = $(this).attr('value');
                $.ajax({
                    type: 'POST',
                    url: '/remove-comment/' + pk + '/',
                    data: {
                        csrfmiddlewaretoken: '{{csrf_token}}',
                    },
                    success: function () {
                        alert('Comment Removed successfully!')
                        window.location.reload()
                    },

                });
            }
        });

        $(document).on('click', '#likes', function(e) {
            e.preventDefault();

            var pk = $(this).attr('value');

            $.ajax({
                type: "POST",
                url: "{% url 'core:likes' %}",
                data: {
                    'pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token}}',
                },
                dataType: "json",
                success: function(response) {
                    $('#like-section').html(response['form'])
                },
                error: function(res, ev) {
                    console.log(res.responseText)
                }
            });
        });
    });

</script>

{% endblock %}

rsbakery/core/templates/core/update.html
{% extends 'users/base.html' %}

{% block body %}

<div class="container mt-3 mb-3">
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h4>Remove Ingredients</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12" id="remove-tab-div">
                    <ul id="remove-block">
                        {% for ingredient in recipe.ingredients.all %}
                        <li>{{ingredient}}<span>
                                <a href="{% url 'core:remove-ingredients' recipe.id ingredient.id %}"
                                    id="{{ingredient.id}}" class="btn"><i class="fas fa-trash"></i></a></span></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <h4>Add Ingredients</h4>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group form-inline ingredient-wrap">
                    <div class="input-group">
                        <input type="text" class="form-control mb-3" name="ingredient" id="recipe-ingredient" />
                        <span class="input-group-append">
                            <a href="" class="form-control btn btn-outline-info add-ingredient mb-3 mr-3"
                                id="add-ingredients"><i class="fas fa-plus"></i></a>
                        </span>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>

    </div>
</div>

{% endblock %}