rsbakery/core/urls.py
from django.urls import path, include
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('create-recipe/', CreateRecipeView.as_view(), name='create-recipe'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='detail'),
    path('update-recipe/<int:pk>/', RecipeUpdateView.as_view(), name='update-recipe'),
    path('delete-recipe/<int:pk>/', RecipeDeleteView.as_view(), name='delete-recipe'),
    path('add/<int:pk>/', UpdateIngredient.as_view(), name='add-ingredients'),
    path('remove/<int:recipe>/<int:ingredient>/', RemoveIngredient.as_view(), name='remove-ingredients'),
    path('recipe-collection/', RecipeCollectionListView.as_view(), name='recipe-collection-list'),
    path('recipe/<int:pk>/add-comment/', AddComment.as_view(), name='add-comment'),
    path('remove-comment/<int:pk>/', RemoveComment.as_view(), name='remove-comment'),
    path('likes/', Likes.as_view(), name='likes'),
    path('update-collections/', UpdateCollectionView.as_view(), name='update-collections'),
    path('contact/', ContactView.as_view(), name='contact-us'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),


    
]

rsbakery/culinary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('products.urls')),
    path('sales/', include('sales.urls')),
    path('users/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rsbakery/products/urls.py
from django.urls import path


from .views import *

app_name = 'products'

urlpatterns = [
    path('products/', ProductListView.as_view(), name="products"),
    path('products/<int:pk>/', ProductDetailView.as_view(), name="products-detail"),

    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path('dashboard/products/', DashboardProductListView.as_view(), name="dashboard-products-list"),
    path('dashboard/products/add/', ProductCreateView.as_view(), name="dashboard-product-add"),
    path('dashboard/products/update/<int:pk>/', ProductUpdateView.as_view(), name="dashboard-product-update"),
    path('dashboard/products/delete/<int:pk>/', ProductDeleteView.as_view(), name="dashboard-product-delete"),

    path('dashboard/raw_material/', RawMaterialListView.as_view(), name="dashboard-raw-material-list"),
    path('dashboard/raw_material/add/', RawMaterialCreateView.as_view(), name="dashboard-raw-material-add"),
    # path('dashboard/raw_material/update/<int:pk>/', RawMaterialUpdateView.as_view(), name="dashboard-raw-material-update"),

    path('dashboard/stock/', StockListView.as_view(), name="dashboard-stock-list"),
    path('dashboard/stock/add/', StockCreateView.as_view(), name="dashboard-stock-add"),
    path('dashboard/stock/update/<int:pk>/', StockUpdateView.as_view(), name="dashboard-stock-update"),
    path('dashboard/stock/delete/<int:pk>/', StockDeleteView.as_view(), name="dashboard-stock-delete"),

    path('dashboard/products/stock/', ProductStockListView.as_view(), name="dashboard-product-stock-list"),
    path('dashboard/products/stock/add/', ProductStockCreateView.as_view(), name="dashboard-product-stock-add"),

    path('get_unit/', get_unit, name="get_unit"),
]

rsbakery/rsbakery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('products.urls')),
    path('sales/', include('sales.urls')),
    path('users/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'users.views.error_404'
handler500 = 'users.views.error_500'
handler403 = 'users.views.error_403'

rsbakery/sales/urls.py
from django.urls import path


from .views import *

app_name = 'sales'

urlpatterns = [
    path('billing/', OrderCreateView.as_view(), name="billing"),
    path('orders/', OrdersListView.as_view(), name="orders"),

    path('get_price/', get_price, name="get_price"),
    path('get_invoice/<int:pk>/', GeneratePdf.as_view(), name="get_invoice"),

]

rsbakery/products/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth import get_user_model
from django.db.models import Q, F

from core.utils import crop_and_save

User = get_user_model()


class BaseTracker(models.Model):
    created_by = models.ForeignKey(
        User, related_name='created_%(class)s', on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class BaseStock(BaseTracker):
    quantity = models.PositiveSmallIntegerField(blank=True, null=True)
    price = models.DecimalField(
        max_digits=8, decimal_places=2, blank=True, null=True)
    validity = models.DateField(blank=True, null=True)
    
    class Meta:
        abstract = True



class Tags(BaseTracker):
    tag = models.CharField(max_length=20)

    def __str__(self):
        return self.tag

class Category(BaseTracker):
    category = models.CharField(max_length=20)

    def __str__(self):
        return self.category


class Product(BaseTracker):
    """Finished Products available for selling"""
    product = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    quantity_available = models.PositiveIntegerField(
        default=0, blank=True, null=True)
    price_before_tax = models.DecimalField(
        max_digits=6, decimal_places=2, blank=True, null=True)
    tax = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    price_after_tax = models.DecimalField(
        max_digits=6, decimal_places=2, blank=True, null=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, blank=True, null=True)
    tags = models.ManyToManyField('Tags')
    status = models.BooleanField(default=True, blank=True, null=True)
    product_discount = models.PositiveSmallIntegerField(
        default=0,
        validators=[MaxValueValidator(10)], blank=True, null=True)
    image = models.ImageField(upload_to='pictures',
                              default='pictures/mypic.jpg')
    weight = models.PositiveSmallIntegerField(blank=True, null=True)
    best_before = models.PositiveSmallIntegerField(blank=True, null=True)
    base_ingredient = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        if self.product:
            return self.product
        return f'Product No. {self.pk}'

    class Meta:
        permissions = (
            ('access_dashboard', 'Access Dashboard'),
        )

    def get_weight(self):
        if self.weight:
            return f'{self.weight} Gms.' 
        return 'N/A'

    def get_status(self):
        if self.status:
            return 'Active'
        return 'Disabled'

    # def get_sale_price_after_discount(self):
    #     if self.product_discount:
    #         return self.price_before_tax * (1-self.product_discount/100)
    #     return self.price_before_tax

    # def get_sale_price_after_tax(self):
    #     if self.price_before_tax:



    def save(self, *args, **kwargs):
        if self.product_discount:
            price_after_discount = self.price_before_tax * (1-self.product_discount/100)
            self.price_after_tax = price_after_discount * (1+self.tax/100)
        else:
            self.price_after_tax = self.price_before_tax * (1+self.tax/100)
        super().save(*args, **kwargs)
        image = crop_and_save(self.image.path, 350, 400)
        image.save(self.image.path)


class ProductStock(BaseStock):
    product = models.ForeignKey(
        'Product', on_delete=models.CASCADE, related_name='product_stock')

    def __str__(self):
        return str(self.product)
    
    def save(self, *args, **kwargs):
        if not self.pk:
            Product.objects.filter(id=self.product_id).update(
                quantity_available=F('quantity_available') + self.quantity)
        super().save(*args, **kwargs)



##### Raw Materials ########

UNITS = (
    (1, 'Grams.'),
    (2, 'Pcs.'),
    (3, 'Milli-Litres.'),
    (4, 'KiloGrams.'),
    (5, 'Litres.'),
)

class RawMaterial(BaseTracker):
    item = models.CharField(max_length=25, blank=True, null=True)
    quantity_available = models.PositiveSmallIntegerField(
        blank=True, null=True)
    unit = models.PositiveSmallIntegerField(
        choices=UNITS, blank=True, null=True)

    def __str__(self):
        return self.item

    def get_unit(self):
        return self.get_unit_display()


class RMStock(BaseStock):
    PAYMENT_CHOICES = (
        ('Done', 'Done'),
        ('Pending', 'Pending'),
    )
    item = models.ForeignKey(
        'RawMaterial', on_delete=models.CASCADE, related_name='rm_stock')
    supplier = models.CharField(max_length=255, blank=True, null=True)
    payment_status = models.CharField(
        max_length=10, choices=PAYMENT_CHOICES, blank=True, null=True)

    class Meta:
        verbose_name = "Raw Material Stock"
        verbose_name_plural = "Raw Material Stock"

    def __str__(self):
        return str(self.item)

    def save(self, *args, **kwargs):
        if not self.pk:
            RawMaterial.objects.filter(id=self.item_id).update(
                quantity_available=F('quantity_available') + self.quantity)
        super().save(*args, **kwargs)

rsbakery/products/views.py
from django.urls import reverse_lazy
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django_filters.views import FilterView

from .models import *
from .forms import *
from .filters import ProductFilter
from core.utils import CustomAuthMixin

############## Helper Function #######################

@login_required
def get_unit(request):
    pk = request.GET.get('pk')
    unit = RawMaterial.objects.get(id=pk).get_unit()
    return JsonResponse({'unit': unit})


# class CustomAuthMixin(LoginRequiredMixin, PermissionRequiredMixin):
#     permission_required = []


############## Product Basic Views #######################

class ProductListView(FilterView):
    model = Product
    template_name = 'products/product_list.html'
    paginate_by = 10
    filterset_class = ProductFilter

    def get_queryset(self):
        query = self.request.GET.get('search', None)
        ctg = self.request.GET.get('ctg', None)
        if ctg:
            return Product.objects.filter(
                Q(category__category__icontains=ctg)
            ).order_by('-id')
        if query:
            return Product.objects.filter(
                Q(product__icontains=query) | Q(category__category__icontains=query) \
                    | Q(tags__tag__icontains=query)
            ).order_by('-id')
        return Product.objects.all().order_by('-id')

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)

class ProductDetailView(DetailView):
    """Open View to show product detail page"""
    model = Product
    template_name = 'products/product_detail.html'

class ProductCreateView(CustomAuthMixin, SuccessMessageMixin, CreateView):
    permission_required = ['products.add_product']
    form_class = ProductForm
    template_name = 'products/add_product.html'
    success_url = reverse_lazy('products:dashboard-product-add')
    success_message = 'Product added Successfully'


class ProductUpdateView(CustomAuthMixin, SuccessMessageMixin, UpdateView):
    permission_required = ['products.change_product']
    model = Product
    form_class = ProductForm
    template_name = 'products/add_product.html'
    success_url = reverse_lazy('products:dashboard-products-list')
    success_message = 'Product updated Successfully'


class ProductDeleteView(CustomAuthMixin, DeleteView):
    permission_required = ['products.change_product']
    model = Product
    success_message = 'Product deleted Successfully'

    def delete(self, request, *args, **kwargs):
        self.get_object().delete()
        messages.success(request, self.success_message)
        payload = {'status': True, 'message': 'Deleted'}
        return JsonResponse(payload)


#################### Dashboard Views #################################
class DashboardView(CustomAuthMixin, TemplateView):
    permission_required = ['products.access_dashboard']
    template_name = 'products/dashboard_main.html'


class DashboardProductListView(CustomAuthMixin, ProductListView):
    permission_required = ['products.access_dashboard']
    template_name = 'products/dashboard_products_list.html'
    paginate_by = 10


#################### Stock Views ######################################

class RawMaterialListView(CustomAuthMixin, ListView):
    permission_required = ['products.view_rawmaterial']
    model = RawMaterial
    template_name = 'products/dashboard_rm_list.html'
    paginate_by = 10

    def get_queryset(self):
        return RawMaterial.objects.all().order_by('-id')
  

class RawMaterialCreateView(CustomAuthMixin, SuccessMessageMixin, CreateView):
    permission_required = ['products.add_rawmaterial']
    form_class = RawMaterialForm
    template_name = 'products/dashboard_raw_material_add.html'
    success_message = 'Item added Successfully'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        html = render_to_string(self.template_name, context=context, request=request)
        return JsonResponse({'html': html})
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.created_by = self.request.user
        instance.save()
        messages.success(self.request, self.success_message)
        return JsonResponse({'status': True})

    def form_invalid(self, form):
        print(form.errors)
        super().form_invalid(form)


class StockListView(CustomAuthMixin, ListView):
    permission_required = ['products.view_rmstock']
    model = RMStock
    template_name = 'products/dashboard_stock_list.html'
    paginate_by = 10

    def get_queryset(self):
        return RMStock.objects.all().order_by('-id')

    
class StockCreateView(CustomAuthMixin, SuccessMessageMixin, CreateView):
    permission_required = ['products.add_rmstock']
    form_class = RMStockForm
    template_name = 'products/dashboard_stock_add.html'
    success_url = reverse_lazy('products:dashboard-stock-add')
    success_message = 'Stock added Successfully'


class StockUpdateView(CustomAuthMixin, SuccessMessageMixin, UpdateView):
    permission_required = ['products.change_rmstock']
    model = RMStock
    form_class = RMStockUpdateForm
    template_name = 'products/dashboard_stock_add.html'
    success_url = reverse_lazy('products:dashboard-stock-list')
    success_message = 'Stock updated Successfully'

class StockDeleteView(CustomAuthMixin, SuccessMessageMixin, DeleteView):
    permission_required = ['products.change_rmstock']
    model = RMStock
    success_message = 'Stock deleted Successfully'

    def delete(self, request, *args, **kwargs):
        self.get_object().delete()
        messages.success(request, self.success_message)
        payload = {'status': True, 'message': 'Deleted'}
        return JsonResponse(payload)


class ProductStockListView(CustomAuthMixin, ListView):
    permission_required = ['products.view_productstock']
    model = ProductStock
    template_name = 'products/dashboard_product_stock.html'
    paginate_by = 10

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')

class ProductStockCreateView(RawMaterialCreateView):
    permission_required = ['products.add_productstock']
    form_class = ProductStockForm
    template_name = 'products/dashboard_product_stock_add.html'
    success_message = 'Item added Successfully'

rsbakery/products/templates/products/_product_snippet.html
{% load static %}
<div class="col-md-3 col-sm-6 p-3">
    <div class="card h-100 clickable shadow-sm" data-id="{{item.id}}">
        <img class="card-img-top" src="{{item.image.url}}" />
        <div class="card-footer prodFooter">
            <div class="d-flex justify-content-between">
                <h5>{{item.product}}</h5>
                <img src="{% static 'veg.svg' %}" class="veg-logo">
            </div>
            <div class="d-flex justify-content-between">
                <p>Weight: {{item.get_weight}}</p>
                <p><strong>&#8377;</strong> {{item.price_after_tax}}</p>
            </div>
        </div>
    </div>
</div>

rsbakery/products/templates/products/add_product.html
{% extends 'products/dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main %}

<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card my-3">
            <div class="card-body formLayout">
                <h5 class="card-title text-center m-3">Add Products</h5>
                <div class="row form-group">
                    <div class="col-md-3 col-sm-6">
                        {{ form.product|as_crispy_field }}
                    </div>
                    <div class="col-md-3 col-sm-6">
                        {{ form.weight|as_crispy_field }}
                    </div>
                    <div class="col-md-3 col-sm-6">
                        {{ form.category|as_crispy_field }}
                    </div>
                    <div class="col-md-3 col-sm-6 file-attachment">
                        {{ form.image |as_crispy_field }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-3 col-sm-6">
                        {{ form.price_before_tax |as_crispy_field }}
                    </div>
                    <div class="col-md-3 col-sm-6">
                        {{ form.tax|as_crispy_field }}
                    </div>
                    <div class="col-md-3 col-sm-6">
                        {{ form.product_discount|as_crispy_field }}
                    </div>
                    <div class="col-md-3 col-sm-6">
                        {{ form.best_before|as_crispy_field }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-3 col-sm-6">
                        {{ form.base_ingredient|as_crispy_field }}
                    </div>
                    <div class="col-md-3 col-sm-6">
                        {{ form.quantity_available|as_crispy_field }}
                    </div>
                    <div class="col-md-3 col-sm-6">
                        {{ form.tags|as_crispy_field }}
                    </div>
                    <div class="col-md-3 col-sm-6">
                        {{ form.status|as_crispy_field }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-12 col-sm-6">
                        {{ form.description|as_crispy_field }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-secondary btn-block">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
<script src="{% static 'js/select2.min.js' %}"></script>

<script>
    $(document).ready(function () {
        $('#id_tags').select2({ width: '100%', dropdownCssClass: "bigdrop" });
    });
</script>

{% endblock main %}

rsbakery/products/templates/products/dashboard_products_list.html
{% extends 'products/dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main %}




<div class="row">
    <div class="col-md-12 py-3 text-right">
        <h2 class="float-left">List of Products</h2>
        <a href="{% url 'products:dashboard-product-add' %}" class="btn btn-outline-secondary btn-sm addStockBtn">
            <span>+</span>Add Products
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead class="thead-custom">
                    <tr>
                        <th>S.No.</th>
                        <th>Name</th>
                        <th>Weight</th>
                        <th>Best Before</th>
                        <th>Price Before Tax</th>
                        <th>Tax (%)</th>
                        <th>Price After Tax</th>
                        <th>Product discount (%)</th>
                        <th>Quantity Available</th>
                        <th>Status</th>
                        <th style="width: 90px;">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                    <tr>
                        <th>{{forloop.counter}}</th>
                        <td>{{item.product}}</td>
                        <td>{{item.weight}}</td>
                        <td>{{item.best_before}}</td>
                        <td>{{item.price_before_tax}}</td>
                        <td>{{item.tax}}</td>
                        <td class="text-right">{{item.price_after_tax}}</td>
                        <td>{{item.product_discount}}</td>
                        <td>{{item.quantity_available}}</td>
                        <td>{{item.get_status}}</td>
                        <td>
                            <form method="POST">
                                {% csrf_token %}
                                <a href="{% url 'products:dashboard-product-update' item.id %}" data-id="{{item.id}}" update="1"
                                    class="updateBtn"><i class="fa fa-pencil"></i></a>

                                <a href="javascript:void(0);" data-id="{{item.id}}" product_delete="1" class="deleteBtn"><i
                                        class="fa fa-trash"></i></a>
                            </form>

                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="11" class="text-center">No Data Found</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6 offset-md-6">
        <div class="pagination float-right pb-3">
            <span class="step-links">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Previous</a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}<span
                                class="sr-only">(current)</span></a>
                    </li>

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Last</a>
                    </li>
                    {% endif %}
                </ul>
            </span>
        </div>
    </div>
</div>




{% endblock main%}

rsbakery/products/templates/products/dashboard_sidebar.html
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  Dashboard <i class="fa fa-caret-down"></i></button>


<div class="collapse navbar-collapse flex-column px-2" id="navbarNavDropdown">
  <ul class="navbar-nav flex-column mr-auto w-100" id="accordian">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'products:dashboard' %}">
        <span><i class="fa fa-bar-chart-o"></i></span> Dashboard<span class="sr-only">(current)</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'products:dashboard-products-list' %}">
        <span><i class="fa fa-dropbox"></i> Products</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#stockAccordian" role="button"
        aria-expanded="false" aria-controls="stockAccordian">
        <span><i class="fa fa-truck"></i> Manage Stocks</span>
      </a>
      <div class="collapse customAccord" data-parent="#accordian" id="stockAccordian">
        <a class="accord-item" href="{% url 'products:dashboard-stock-list' %}">Raw Materials</a>
        <a class="accord-item" href="{% url 'products:dashboard-product-stock-list' %}">Products</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#billingAccordian" role="button"
        aria-expanded="false" aria-controls="billingAccordian">
        <span><i class="fa fa-dollar"></i> Billing / Invoices</span>
      </a>
      <div class="collapse customAccord" data-parent="#accordian" id="billingAccordian">
        <a class="accord-item" href="{% url 'sales:billing' %}">Generate Invoice</a>
        <a class="accord-item" href="{% url 'sales:orders' %}">Orders</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">
        <span><i class="fa fa-clipboard"></i> Posts</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">
        <span><i class="fa fa-users"></i></span> Customers
      </a>
    </li>
  </ul>
  
  
  <ul class="navbar-nav flex-column mr-auto w-100" id="accordian">
    <h6 class="dashboardHeading flex-column p-3">Saved Reports</h6>
    <li class="nav-item">
      <a class="nav-link" href="#">
        <span><i class="fa fa-bar-chart-o"></i></span> Current Month</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">
        <span><i class="fa fa-bar-chart-o"></i></span> Last Month</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">
        <span><i class="fa fa-bar-chart-o"></i></span> Last Year</span>
      </a>
    </li>
</div>

rsbakery/products/templates/products/product_detail.html
{% extends 'users/base.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="row py-4">
        <div class="col-md-5">
            <div class="row">
                <div class="col-md-12 pb-4">
                    <div class="detailImg">
                        <img class="card-img-top" src="{{object.image.url}}">
                        <img class="veg-logo" src="{% static 'veg.svg' %}">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-7 heading">
            <div class="detail-heading">
                <h3>{{object.product | capfirst}}</h3>
            </div>
            <div class="detail-price py-3">
                <h2><strong>&#8377;</strong> {{object.price_after_tax}}</h2>
            </div>
            <div class="detail-description">
                <h4>About Product</h4>
                <p>{{object.description}}</p>
            </div>

                    

                    

                    


            
            
        </div>
    </div>
    
</div>
{% endblock body %}

{% block scripts %}
<script>
    $(document).ready(function (e) {
        $(document).on('click', '#add-to-collections', function (e) {
            e.preventDefault();
            var id = $(this).attr('value');

            $.ajax({
                type: "POST",
                url: "{% url 'core:update-collections' %}",
                data: {'pk': id, 'csrfmiddlewaretoken': '{{csrf_token}}'},
                dataType: 'json',
                success: function (response) {
                    $('#collections-section').html(response['form'])

                },
            });
        });

        $(document).on('click', '#login-alert', function () {
            alert('You must be logged-in to use this feature')
        });

        $(document).on('click', '.delete-btn', function (e) {
            e.preventDefault();
            let confirmation = confirm('Are you sure you want to delete this comment?');
            if (confirmation) {
                var pk = $(this).attr('value');
                $.ajax({
                    type: 'POST',
                    url: '/remove-comment/' + pk + '/',
                    data: {
                        csrfmiddlewaretoken: '{{csrf_token}}',
                    },
                    success: function () {
                        alert('Comment Removed successfully!')
                        window.location.reload()
                    },

                });
            }
        });

        $(document).on('click', '#likes', function(e) {
            e.preventDefault();

            var pk = $(this).attr('value');

            $.ajax({
                type: "POST",
                url: "{% url 'core:likes' %}",
                data: {
                    'pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token}}',
                },
                dataType: "json",
                success: function(response) {
                    $('#like-section').html(response['form'])
                },
                error: function(res, ev) {
                    console.log(res.responseText)
                }
            });
        });
    });

</script>

{% endblock %}