rsbakery/core/urls.py
from django.urls import path, include
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('create-recipe/', CreateRecipeView.as_view(), name='create-recipe'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='detail'),
    path('update-recipe/<int:pk>/', RecipeUpdateView.as_view(), name='update-recipe'),
    path('delete-recipe/<int:pk>/', RecipeDeleteView.as_view(), name='delete-recipe'),
    path('add/<int:pk>/', UpdateIngredient.as_view(), name='add-ingredients'),
    path('remove/<int:recipe>/<int:ingredient>/', RemoveIngredient.as_view(), name='remove-ingredients'),
    path('recipe-collection/', RecipeCollectionListView.as_view(), name='recipe-collection-list'),
    path('recipe/<int:pk>/add-comment/', AddComment.as_view(), name='add-comment'),
    path('remove-comment/<int:pk>/', RemoveComment.as_view(), name='remove-comment'),
    path('likes/', Likes.as_view(), name='likes'),
    path('update-collections/', UpdateCollectionView.as_view(), name='update-collections'),
    path('contact/', ContactView.as_view(), name='contact-us'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),


    
]

rsbakery/culinary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('products.urls')),
    path('sales/', include('sales.urls')),
    path('users/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rsbakery/products/urls.py
from django.urls import path


from .views import *

app_name = 'products'

urlpatterns = [
    path('products/', ProductListView.as_view(), name="products"),
    path('products/<int:pk>/', ProductDetailView.as_view(), name="products-detail"),

    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path('dashboard/products/', DashboardProductListView.as_view(), name="dashboard-products-list"),
    path('dashboard/products/add/', ProductCreateView.as_view(), name="dashboard-product-add"),
    path('dashboard/products/update/<int:pk>/', ProductUpdateView.as_view(), name="dashboard-product-update"),
    path('dashboard/products/delete/<int:pk>/', ProductDeleteView.as_view(), name="dashboard-product-delete"),

    path('dashboard/raw_material/', RawMaterialListView.as_view(), name="dashboard-raw-material-list"),
    path('dashboard/raw_material/add/', RawMaterialCreateView.as_view(), name="dashboard-raw-material-add"),
    # path('dashboard/raw_material/update/<int:pk>/', RawMaterialUpdateView.as_view(), name="dashboard-raw-material-update"),

    path('dashboard/stock/', StockListView.as_view(), name="dashboard-stock-list"),
    path('dashboard/stock/add/', StockCreateView.as_view(), name="dashboard-stock-add"),
    path('dashboard/stock/update/<int:pk>/', StockUpdateView.as_view(), name="dashboard-stock-update"),
    path('dashboard/stock/delete/<int:pk>/', StockDeleteView.as_view(), name="dashboard-stock-delete"),

    path('dashboard/products/stock/', ProductStockListView.as_view(), name="dashboard-product-stock-list"),
    path('dashboard/products/stock/add/', ProductStockCreateView.as_view(), name="dashboard-product-stock-add"),

    path('get_unit/', get_unit, name="get_unit"),
]

rsbakery/rsbakery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('products.urls')),
    path('sales/', include('sales.urls')),
    path('users/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'users.views.error_404'
handler500 = 'users.views.error_500'
handler403 = 'users.views.error_403'

rsbakery/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from users import views as user_views


app_name = 'users'


urlpatterns = [
    # path('register/', user_views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.ProfileView.as_view(), name='profile'),
    path('profile-update/<int:pk>/',
         user_views.ProfileUpdate.as_view(), name='update_profile'),
    path('activate/<uidb64>/<token>/',
         user_views.activate_account, name='activate'),
    path('password-change/', user_views.UserPasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name="password_change_done"),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('users:password_reset_done'),
        email_template_name='users/password_reset_email.html'
    ), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),

    path('password-reset/complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

rsbakery/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.conf import settings
from django.shortcuts import reverse


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Email required for Registration')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        user = self.create_user(email=email, password=password)
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user


class UserModel(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    image = models.ImageField(upload_to='profiles', default='profiles/default_profile.jpg')
    about_me = models.CharField(max_length=255, blank=True, null=True) 
    location = models.CharField(max_length=25, blank=True, null=True)
    phone = models.CharField(max_length=10, blank=True, null=True)  

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

rsbakery/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from PIL import Image
from django.core.files import File
from .models import Profile

class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

    # To make name fields required
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['password1'].help_text = None


class ProfileForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'about_me', 'location', 'phone', 'image', 'x', 'y', 'width', 'height', )

    def save(self):
        profile = super(ProfileForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        img = Image.open(profile.image)
        cropped_image = img.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(profile.image.path)

        return profile

rsbakery/users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import get_user_model, login
from django.views.generic import View, UpdateView, DetailView, TemplateView
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy

from .forms import RegisterForm, ProfileForm
from .models import Profile
from .tokens import account_activation_token

def error_404(request, exception):
    data = {}
    return render(request, 'users/error_404.html', data)


def error_500(request):
    data = {}
    return render(request, 'users/error_500.html', data)

def error_403(request, exception):
    data = {}
    return render(request, 'users/error_403.html', data)

class OwnerOnlyMixin:
    """Authorize only the owner of the object to update or delete an item"""
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user == request.user:
            return super().dispatch(request, *args, **kwargs)
        else:
            return HttpResponse('Unauthorized', status=401)

class RegisterView(View):
    """To register a new user with email-verification"""
    def get(self, request, *args, **kwargs):
        form = RegisterForm()
        return render(request, 'users/register.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = RegisterForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            user.profile.first_name = first_name
            user.profile.last_name = last_name
            user.save()
            # registraion via email verification
            current_site = get_current_site(request)
            email_subject = "Please complete you registration"
            message = render_to_string('users/user_activation.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(email_subject, message, to=[to_email])
            email.send()
            messages.success(request, 'Activation link sent you your email ID. Please check you inbox')
            return redirect('users:login')
        # messages.error(request, 'Sorry username already taken')
        return render(request, 'users/register.html', {'form': form})

def activate_account(request, uidb64, token):
    """To activate the user profile after validating the token"""
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = get_user_model().objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, get_user_model().ObjectDoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "Your account has been activated successfully!")
        return redirect('users:profile')
    
    messages.error(request, 'Activation link is invalid!')
    return redirect('users:register')


class ProfileView(LoginRequiredMixin, TemplateView):
    """To display the User Profile"""
    # model = Profile
    template_name = 'users/profile.html'


class ProfileUpdate(LoginRequiredMixin, OwnerOnlyMixin, UpdateView):
    """To update the user profile"""
    model = Profile
    # fields = ('first_name', 'last_name', 'image', 'location', 'about_me', 'phone')
    form_class = ProfileForm
    success_url = reverse_lazy('users:profile')


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('users:password_change_done')

rsbakery/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RS Bakery</title>
    <!-- bootstrap  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/cropper.css' %}">
    <link rel="stylesheet" href="{% static 'jquery_ui/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'jquery_ui/jquery-ui.structure.css' %}">
    <link rel="stylesheet" href="{% static 'jquery_ui/jquery-ui.theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
    <!-- fontawesome -->
    <script src="{% static 'js/fontawesome.js' %}"></script>
    <script src="{% static 'js/cropper.js' %}"></script>
    <script src="{% static 'js/jquery-cropper.js' %}"></script>
    <script src="{% static 'jquery_ui/jquery-ui.js' %}" type="text/javascript"></script>
    <script src="{% static 'jquery_ui/jquery.ui.touch-punch.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/custom.js' %}"></script>

    <script>
        $(document).ready(function () {
            var max_fields = 20;
            var tag_wrapper = $(".tag-wrap");
            var ingredient_wrapper = $(".ingredient-wrap");
            var add_tag = $(".add-tag");
            var add_ingredient = $(".add-ingredient");

            var x = 1;
            $(add_tag).click(function (e) {
                e.preventDefault();
                if (x < max_fields) {
                    x++;
                    $(tag_wrapper).append('<div class="form-inline"><input type="text" class="form-control mr-3 mb-3" name="tag"><a href="#" class="remove-tag mb-3">Remove</a></div>')
                }
            });
            $(tag_wrapper).on("click", ".remove-tag", function (e) {
                e.preventDefault();
                $(this).parent('div').remove();
                x--;
            });

            $(add_ingredient).click(function (e) {
                e.preventDefault();
                if (x < max_fields) {
                    x++;
                    $(ingredient_wrapper).append('<div class="form-inline"><input type="text" class="form-control mr-3 mb-3" name="ingredient"><a href="#" class="remove-ingredient mb-3">Remove</a></div>')
                }
            });

            $(ingredient_wrapper).on("click", ".remove-ingredient", function (e) {
                e.preventDefault();
                $(this).parent('div').remove();
                x--;
            });
        });
    </script>

</head>

<body>
    <div id="baseDiv">
        <div id="mainDiv">
            {% include 'users/header.html' %}

            <!-- body block -->
            {% block body %}{% endblock %}

            <!-- scripts block -->
            {% block scripts %}{% endblock %}
        </div>
    </div>
    <!-- Footer -->
    <footer class="footer">

        <!-- Footer Links -->
        <div class="container text-center text-md-left">
            <!-- Grid row -->
            <div class="row">
                <!-- Grid column -->
                <div class="col-md-6 mt-md-0 mt-3">
                    <!-- Content -->
                    <h5 class="text">RS Bakery</h5>
                    <p>We deal in all kinds of Bakery products like Cakes, Pastries, Breads, Buns, Cookies, Sandwich, Pizza etc.</p>
                    <p>All our products are <strong>100 % Vegetarian</strong></p>
                    <p>We also accept bulk orders</p>
                </div>
                <!-- Grid column -->

                <hr class="clearfix w-100 d-md-none pb-3">

                <!-- Grid column -->
                <div class="col-md-3 mb-md-0 mb-3">

                    <!-- Links -->
                    <h5 class="text">Site Map</h5>

                    <div class="footer-links">
                        <a href="{% url 'core:index' %}">Home</a>
                        <a href="{% url 'products:products' %}">Products</a>
                        <a href="{% url 'core:recipes' %}">Posts</a>
                        <a href="{% url 'core:about-us' %}">About Us</a>
                        <a href="{% url 'core:contact-us' %}">Contact Us</a>
                    </div>

                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 mb-md-0 mb-3">

                    <!-- Links -->
                    <h5 class="text">Visit us at</h5>

                    <div class="socialLinks">
                        <a href="#!" class="mx-1"><i class="fa fa-facebook-square fa-2x"></i></a>
                        <a href="#!" class="mx-1"><i class="fa fa-instagram fa-2x"></i></a>
                        <a href="#!" class="mx-1"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </div>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
        <!-- Footer Links -->

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© {% now 'Y' %} Copyright:
            <a href="#"> RSBakery</a>
        </div>
        <!-- Copyright -->

    </footer>

    <script>
        window.onload = function () {
            var url = "{{request.path}}"
            $(`a[href='${url}']`).closest('li').addClass('active active-accord')
            $(`a[href='${url}']`).closest('.customAccord').addClass('show')
        }
    </script>

</body>


</html>

rsbakery/users/templates/users/error_500.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>500</h3>
            <p>Internal Server Error</p>
            

        </div>
    </div>
</div>

{% endblock %}

rsbakery/users/templates/users/header.html
{% load static %}
<!-- navbar -->
<nav class="navbar navbar-expand-md navbar-dark navbar-secondary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:index' %}"><img width="130px" height="55px" src="{% static 'logo_brown_hat_orange.svg' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-ctrl"
            aria-controls="navbar-ctrl" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar-ctrl">
            <ul class="navbar-nav ml-left">
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'core:index' %}" class="btn btn-simple">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'products:products' %}" class="btn btn-simple">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'core:recipes' %}" class="btn btn-simple">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'core:about-us' %}" class="btn btn-simple">About
                        Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'core:contact-us' %}" class="btn btn-simple">Contact
                        Us</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                {% if perms.products.access_dashboard %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'products:dashboard' %}" class="btn btn-simple">Dashboard</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'core:create-recipe' %}" class="btn btn-simple">Add
                        Post</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Hello {{user.profile.first_name}}</a>
                    <div class="dropdown-menu" aria-labelledby="profileDropdown">
                        <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'users:password_change' %}">Change Password</a>
                        <a class="dropdown-item" href="{% url 'core:recipe-collection-list' %}">My Recipe
                            Collection</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#">Sign Up</a>
                </li> -->
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

rsbakery/users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

{% include 'users/_messages.html' %}

<div class="imageContainer loginimg">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class=" loginForm shadow">
                    <div class="card-header pb-0">
                        <div class="card-title">
                            <h2>Login</h2>
                        </div>
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="card-body">
                            {{form|crispy}}
                            <div class="text-right p-1">
                                <a href="{% url 'users:password_reset' %}" class="float-left pt-1 text-orange">Forgot Password?</a>
                                <button type="submit" class="btn btn-outline-orange px-4">Login</button>
                            </div>
    
                        </div>
                        <!-- <div class="card-footer py-3">
                            <div class="d-flex justify-content-center links">
                                Don't have an account?<a href="#" class="px-1"> Sign Up</a>
                            </div>
                        </div> -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

rsbakery/users/templates/users/logout.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
{% include 'users/_messages.html' %}

<div class="container">
    <div class="row mt-4 mb-4">
        <div class="col-md-6 offset-md-3">
            <div class="card shadow mt-4 bg-white rounded">
                <div class="card-header">
                    <div class="card-title">
                        <h5>Logout</h5>
                    </div>
                </div>
                <div class="card-body">
                    <p>Thanks for visiting us. See you around Soon!</p>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

rsbakery/users/templates/users/password_change_done.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-4">
            <div class="card shadow">
                <div class="card-header ">
                    <div class="card-title">
                        <h5>Password Change</h5>
                    </div>
                </div>
                <div class="card-body">
                    <p>Password Changed Successfully</p>
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

rsbakery/users/templates/users/password_change_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-4">
            <div class="card shadow">
                <div class="card-header ">
                    <div class="card-title">
                        <h5>Change Password</h5>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

rsbakery/users/templates/users/password_reset_complete.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="alert alert-info">
        Your Password has been reset successfully.
    </div>
    <a href="{% url 'users:login' %}">Login</a>
</div>


{% endblock %}

rsbakery/users/templates/users/password_reset_done.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="alert alert-info">
        Password reset link has been sent to your registered email. Please check your inbox.
    </div>
</div>


{% endblock %}

rsbakery/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
	
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
	
{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

rsbakery/users/templates/users/password_reset_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 my-4">
            <div class="card shadow">
                <div class="card-header ">
                    <div class="card-title">
                        <h5>Password Reset</h5>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-outline-info float-right">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

rsbakery/users/templates/users/profile_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-4">
            <div class="card shadow">
                <div class="card-header ">
                    <div class="card-title">
                        <h5>Update Profile</h5>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" id="id_form">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="" id="image" style="max-width: 100%;">
      </div>
      <div class="modal-footer">
        <div class="btn-group pull-left" role="group">
          <button type="button" class="btn btn-default js-zoom-in">
            Zoom-in
          </button>
          <button type="button" class="btn btn-default js-zoom-out">
            Zoom-out
          </button>
        </div>
        <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

rsbakery/users/templates/users/user_activation.html
{% autoescape off %}
Hi {{ user.first_name | capfirst }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

Regards,
Team RSBakery
{% endautoescape %}